### ISSUE TITLE
InternalServerError for null field

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#186]
![image](https://cloud.githubusercontent.com/assets/41906/9694602/06027e62-530f-11e5-85bf-934c79571bd8.png)

https://ccapi-dev.18f.gov/v1/schools/?id=196431&fields=2013.student.part_time_share

I think there might be a mapping error here, but this also should give us a more friendly response

![image](https://cloud.githubusercontent.com/assets/41906/9694619/39970b4e-530f-11e5-90fe-ac266417d85b.png)

**Comment by reneighbor** [comment]
Working with Caleb

**Comment by ultrasaurus** [comment]
this is working on the dev server now:  https://ccapi-dev.18f.gov/v1/schools/?id=196431&fields=2013.student.part_time_share

```
{
  "metadata": {
  "total": 1,
  "page": 0,
  "per_page": 20
},
"results": [
    {
       "2013.student.part_time_share": 0
    }
  ]
}
```

**Comment by ultrasaurus** [comment]
This query actually results as a null result:

https://ccapi-dev.18f.gov/v1/schools/?id=196431&fields=2013.student.demographics.unemployment

```
2015-09-24T23:03:51.11-0400 [App/0]      ERR 2015-09-25 03:03:51 - NoMethodError - undefined method `keys' for nil:NilClass:
2015-09-24T23:03:51.11-0400 [App/0]      ERR 	/home/vcap/app/lib/data_magic.rb:98:in `block in search'
2015-09-24T23:03:51.11-0400 [App/0]      ERR 	/home/vcap/app/lib/data_magic.rb:93:in `map'
2015-09-24T23:03:51.11-0400 [App/0]      ERR 	/home/vcap/app/lib/data_magic.rb:93:in `search'
```

**Comment by reneighbor** [comment]
couldn't reproduce - releasing bug

**Comment by ultrasaurus** [comment]
my guess is this only fails with nested data, though would be good to have tests that cover both non-nested and nested data

**Comment by ultrasaurus** [comment]
I believe this is resolved, just needs verification
