### ISSUE TITLE
NoMethodError: undefined method `each' for "/home/vcap/app/app/stylesheets":String

### ISSUE THREAD

**Issue by dnesting** [18F/open-data-maker#219]
```
NoMethodError: undefined method `each' for "/home/vcap/app/app/stylesheets":String

…uby/2.2.0/gems/sass-3.4.16/lib/sass/plugin/compiler.rb: 251:in `file_list'
…uby/2.2.0/gems/sass-3.4.16/lib/sass/plugin/compiler.rb: 205:in `update_stylesheets'
…/bundle/ruby/2.2.0/gems/sass-3.4.16/lib/sass/plugin.rb:  82:in `update_stylesheets'
…/bundle/ruby/2.2.0/gems/sass-3.4.16/lib/sass/plugin.rb:  54:in `check_for_updates'
…le/ruby/2.2.0/gems/sass-3.4.16/lib/sass/plugin/rack.rb:  51:in `call'
…ack-protection-1.5.3/lib/rack/protection/xss_header.rb:  18:in `call'
…rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:  18:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/base.rb:  49:in `call'
…gems/rack-protection-1.5.3/lib/rack/protection/base.rb:  49:in `call'
…-protection-1.5.3/lib/rack/protection/frame_options.rb:  31:in `call'
…dor/bundle/ruby/2.2.0/gems/rack-1.5.5/lib/rack/head.rb:  11:in `call'
…/ruby/2.2.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:  21:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
…ndle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
…ndle/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
….0/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:  84:in `block in call'
….0/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:  75:in `each'
….0/gems/padrino-core-0.12.5/lib/padrino-core/router.rb:  75:in `call'
…/ruby/2.2.0/gems/puma-2.13.4/lib/puma/configuration.rb:  78:in `call'
…/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb: 541:in `handle_request'
…/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb: 388:in `process_client'
…/bundle/ruby/2.2.0/gems/puma-2.13.4/lib/puma/server.rb: 270:in `block in run'
…le/ruby/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb: 106:in `call'
…le/ruby/2.2.0/gems/puma-2.13.4/lib/puma/thread_pool.rb: 106:in `block in spawn_thread'
```

We've only seen a single instance of this error.  I believe this is due to a multi-threading race condition and I've opined on sass/sass#1827 to address upstream.  If so, a workaround would be for us to use the array form of this in lib/sass_initializer.rb:

```
# Sass::Plugin.options[:template_location] = Padrino.root("app/stylesheets")
Sass::Plugin.options[:template_location] = [
    Padrino.root("app/stylesheets"), Padrino.root("public/stylesheets")]
```

**Comment by dnesting** [comment]
My upstream fix for this was accepted and is now in saas stable.  I expect it to be in saas release 3.4.20 later this month.
