### ISSUE TITLE
latest dev branch fails to deploy on Cloud Foundry

### ISSUE THREAD

**Issue by ultrasaurus** [18F/open-data-maker#268]
```
2016-01-12T09:55:33.41-0800 [App/0]      OUT [29] ! Unable to load application: NameError: uninitialized constant Module::EagerLoader
2016-01-12T09:55:33.41-0800 [App/0]      ERR /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.11/lib/aws-sdk-core.rb:292:in `eager_autoload!': uninitialized constant Module::EagerLoader (NameError)
2016-01-12T09:55:33.41-0800 [App/0]      ERR 	from /home/vcap/app/lib/data_magic.rb:311:in `init'
2016-01-12T09:55:33.41-0800 [App/0]      ERR 	from /home/vcap/app/app/app.rb:27:in `<class:App>'
2016-01-12T09:55:33.41-0800 [App/0]      ERR 	from /home/vcap/app/app/app.rb:4:in `<module:OpenDataMaker>'
2016-01-12T09:55:33.41-0800 [App/0]      ERR 	from /home/vcap/app/app/app.rb:3:in `<top (required)>'
2016-01-12T09:55:33.41-0800 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/padrino-core-0.12.5/lib/padrino-core/reloader.rb:95:in `require'
```

**Comment by yozlet** [comment]
We worked out that this was due to bad code in #256, in particular the new [`read_from_s3`](https://github.com/18F/open-data-maker/blob/a1ca437353789a74a3e18058383b284fbbb7c922/lib/data_magic/config.rb#L299-L310) using S3 client methods that actually don't exist. @ultrasaurus is working on a fix.
